version: '3.8'

services:
  backend:
    build: .
    container_name: charity-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
      - devops-network
    depends_on:
      - mongo
    restart: unless-stopped

  frontend:
    build: ./client
    container_name: charity-frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    networks:
      - devops-network
    depends_on:
      - backend
    restart: unless-stopped

  mongo:
    image: mongo:latest
    container_name: charity-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - devops-network
    restart: unless-stopped

networks:
  devops-network:
    external: true

volumes:
  mongo_data:
